hw1
constZhur/java-backend-course-2023 pull request #1
Opened 2024-02-19 18:22 UTC by constZhur

2024-02-24 16:56 UTC, lwbeamer requested changes

2024-02-24 16:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +
Обычно в класс с main методом  в спринге ничего не внедряют, да и это не нужно здесь, ведь можно прописать `@PostConstruct` сразу в `MyTelegramBot`

2024-02-24 16:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +    }
коммент выше относится и сюда тоже)

2024-02-24 16:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/messageHandler/UserMessageProcessorImpl.java
> +        return update.message().text() == null;
У update всегда есть message? Если api этого не гарантирует, то здесь потенциальный NullPointerException)

2024-02-24 16:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/messageHandler/UserMessageProcessorImpl.java
> +        } else if (isCommand(update)) {
isCommand кажется ненужным, потому что потом ты все равно проверяешь команду на supports()

2024-02-24 16:56 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/messageHandler/UserMessageProcessorImpl.java
> +                currentCommand = command;
Представь, что пришло один юзер отправил` /track`, в `currentCommand` будет `track` и ему придет предложение ввести ссылку. После это другой юзер отправил` /help`, в `currentCommand` будет `help`. Первый после этого отправил ссылку получил сообщение о неверной команде, потому что `isInputRequired()` вернуло false. Надо фиксануть) Если я не прав - напиши почему

2024-02-24 21:25 UTC, constZhur commented on bot/src/main/java/edu/java/bot/messageHandler/UserMessageProcessorImpl.java
> +                currentCommand = command;
Ты прав, но из идей кроме костыля в виде Map, который будет хранить id чата, как ключ, и текущую команду, ничего не приходит.

2024-02-25 13:24 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/messageHandler/UserMessageProcessorImpl.java
> +                currentCommand = command;
Либо так либо присылать ссылку сразу с командой track, либо присылать ссылку как reply (но там скорее всего будет так же проблема, не уверен)

Но в целом вариант с мапой юзер-состояние как ты написал выглядит норм. Единственное, что при перезапуске приложение оно сбросится, но это точно лучше чем некорректное поведение как сейчас.

Какой из вариатов реализовать - на твой выбор, главное чтобы нормально обрабатывался этой кейс)

2024-02-29 15:10 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/commands/TrackCommand.java
> +    }
Поправь если я не так понял, но кажется ты это уже проверяешь ссылку в LinkParser, то есть в итоге одну и ту же проверку делаешь дважды

2024-02-29 15:11 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/messageHandler/UserMessageProcessorImpl.java
> +        long chatId = update.message().chat().id();
Все еще ловишь здесь потенциальный NullPointerException если update == null или message == null. Нужно фиксануть

2024-02-29 15:13 UTC, lwbeamer commented
ДЗ 1 принял, комменты проверю в следующей

2024-02-29 15:31 UTC, constZhur commented on bot/src/main/java/edu/java/bot/messageHandler/UserMessageProcessorImpl.java
> +                currentCommand = command;
Реализовал одной командой

2024-02-29 20:16 UTC, merged