Hw10
constZhur/java-backend-course-2023 pull request #11
Opened 2024-04-21 14:18 UTC by constZhur

2024-04-25 11:41 UTC, lwbeamer commented on bot/bot.Dockerfile
> +ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
а просто `ENTRYPOINT exec java -jar /bot.jar` не стартует? Кажется лишним

2024-04-25 11:41 UTC, lwbeamer commented on scrapper/scrapper.Dockerfile
> +ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
аналогично

2024-04-25 11:42 UTC, lwbeamer requested changes
<img width="223" alt="image" src="https://github.com/constZhur/java-backend-course-2023/assets/73843667/1b108048-7ad1-48c6-aa46-b00a1c84e988">
вижу один образ, это бот или скраппер? Где второй?)

2024-04-27 14:02 UTC, constZhur commented
@lwbeamer

Вроде все исправил

2024-05-01 09:40 UTC, merged