hw3
constZhur/java-backend-course-2023 pull request #3
Opened 2024-03-03 20:40 UTC by constZhur

2024-03-08 18:55 UTC, lwbeamer requested changes

2024-03-08 18:55 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/client/WebScrapperClient.java
> +    Void registerChat(Long id);
класс `Void` используется например в рефлексии или если нужно передать его в generic (как например у тебя в ResponseEntity<Void>), но по-дефолту для ничего не возвращающих методов принято использовать `void` (с маленькой буквы). С какой целью именно `Void` использовал здесь и в других местах?

2024-03-08 18:55 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/BotExceptionController.java
> +        }
Не критично, но Java позволяет сделать это в одну строку используя Stream API

2024-03-08 18:55 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/BotExceptionController.java
> +            .body(createError(error, error.getMessage(), BAD_REQUEST));
Тело методов одинаковое, можно объединить в один, указав внутри `@ExceptionHandler(...)` через запятую несколько классов, а в параметры метода принять `Exception`. Сильно сократишь код

2024-03-08 18:55 UTC, lwbeamer commented on bot/pom.xml
> +        </dependency>
Уверен что это нужно?

2024-03-08 18:55 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/BotExceptionController.java
> +public class BotExceptionController {
Добавь в конце постфикс Advice или ExceptionHandler, в идеале еще закинуть в подпакет соответствующий, ведь это не контроллер. В начале кажется неважным, но если не обращать внимания, то навигация по проекту и общая читаемость сильно упадут

2024-03-08 18:55 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/dto/AddLinkRequest.java
> +package edu.java.bot.dto;
В scrapper у тебя разделение dto по пакетам request/response. Здесь тоже будет удобно

2024-03-08 18:55 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperApiExceptionController.java
> +    }
Аналогично одному из комментов выше можно схлопнуть в один метод

2024-03-08 18:55 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/clients/impl/BotClient.java
> +            .bodyToMono(HttpStatus.class)
В конце ведь все равно `HttpStatus` возвращем, тогда зачем преобразовывать в `BotApiErrorResponse`? К тому же есть `ApiErrorResponse`, у которого все поля идентичны?

2024-03-16 19:04 UTC, constZhur commented on bot/pom.xml
> +        </dependency>
Я случайно, сделал импорт какого-то класса, который был мне нужен из другого модуля

2024-03-24 15:15 UTC, merged