hw6
constZhur/java-backend-course-2023 pull request #6
Opened 2024-03-24 19:41 UTC by constZhur

2024-03-29 17:19 UTC, lwbeamer requested changes
> Сделайте интеграцию клиентов, которые были написаны в прошлом задании, и получите готовое рабочее приложение.

помимо тестов на jpa (и часть на jdbc) этого задания тоже на нашел - нужно чтоб команды в боте уже были реализованы, чтоб при вводе команды в бота полностью весь процесс выполнялся с походом в скраппер, работой с бд и т.д.

2024-03-29 17:19 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/configuration/JdbcAccessConfiguration.java
> +    public JdbcUserService jdbcUserService(JdbcUserRepository userRepository) {
Спринг конечно поймет что внедрять, но давай здесь возвращать интерфейс, чтобы было явно видно контракт

2024-03-29 17:19 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/configuration/JdbcAccessConfiguration.java
> +    public JdbcLinkService jdbcLinkService(JdbcLinkRepository linkRepository, JdbcUserService userService) {
Здесь и в JPA конфигурации аналогично

2024-03-29 17:19 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperApiController.java
> +    private final JdbcUserService userService;
Ты внедряешь реализацию вместо абстракции. Тогда переключение jpa/jdbc вообще теряет смысл. Внедряй типы LinkService и UserService

2024-03-29 17:19 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcLinkRepository.java
> +@Component
У тебя независимо от выбранного типа dao (jpa/jdbc) будет все равно создаваться этот бин, потому что есть эта аннотация. Нужно убрать здесь и в других местах, чтобы бин  регистрировался исключительно через конфигурацию при выбранном jdbc

2024-03-29 17:19 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/repository/jdbc/JdbcUserRepository.java
> +@Component
Здесь аналогично

2024-03-29 17:19 UTC, lwbeamer commented on scrapper/src/test/java/edu/java/scrapper/integration/JdbcUserRepositoryTest.java
> +}
?

2024-03-29 17:19 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/service/jpa/JpaLinkService.java
> +    }
Почему в этом классе половина методов не реализована?)

2024-04-07 10:45 UTC, constZhur commented on scrapper/src/main/java/edu/java/service/jpa/JpaLinkService.java
> +    }
Проверь, пожалуйста, я все исправил

2024-04-07 12:35 UTC, merged