hw7
constZhur/java-backend-course-2023 pull request #7
Opened 2024-03-31 20:12 UTC by constZhur

2024-04-07 12:02 UTC, lwbeamer requested changes
Testov net?

2024-04-07 17:06 UTC, constZhur commented
> Testov net?

Добавил тесты

Есть один вопрос по поводу реализации: 
Из-за того, что параметры Retry из applicatiom.yaml конфигурируются, пришлось написать всем клиентам доп конструкторы, которые используются только в тестах для ручной конфигурации Retry. Это костыль. Как это можно решить?

2024-04-11 13:51 UTC, lwbeamer commented
> Из-за того, что параметры Retry из applicatiom.yaml конфигурируются, пришлось написать всем клиентам доп конструкторы, которые используются только в тестах для ручной конфигурации Retry. Это костыль. Как это можно решить?

А разве сами проперти не подтягиваются? SpringBootTest должен делать всю работу по идее

2024-04-11 13:51 UTC, lwbeamer commented
Чтобы параметры Retry сами внедрились как это в продовом коде происходит

2024-04-11 15:06 UTC, constZhur commented
> Чтобы параметры Retry сами внедрились как это в продовом коде происходит

Хорошо, я поправлю на ветке hw9.

2024-04-11 15:06 UTC, merged